/**
 * SkillChain AI Evaluation System
 * 
 * Deterministic rubric-based scoring algorithm that works 100% offline.
 * No external APIs required - evaluates answers based on keyword matching,
 * synonym expansion, and coherence heuristics.
 * 
 * Scoring breakdown:
 * - Keyphrase matching: up to 90 points (configurable per skill)
 * - Length/coherence bonus: up to 10 points
 * - Minimum word count penalty: -10 points if < 30 words
 */

import skills from '../data/skills.json';

/**
 * Preprocess text for matching
 * - Lowercase
 * - Remove punctuation
 * - Normalize whitespace
 */
function preprocess(text) {
    return text
        .toLowerCase()
        .replace(/[.,!?;:'"()\[\]{}]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}

/**
 * Count words in a string
 */
function wordCount(text) {
    return text.split(/\s+/).filter(w => w.length > 0).length;
}

/**
 * Check if text contains a phrase or any of its synonyms
 */
function containsPhrase(text, phrase) {
    return text.includes(phrase.toLowerCase());
}

/**
 * AI-Generated Content Detection
 * 
 * Uses multiple heuristics to detect if an answer was generated by ChatGPT or other LLMs.
 * Returns a confidence score (0-100) and specific flags.
 */
const AI_PHRASES = [
    // Common ChatGPT phrases
    'it\'s important to note',
    'it is important to note',
    'it\'s worth noting',
    'it is worth mentioning',
    'in conclusion',
    'to summarize',
    'in summary',
    'let me explain',
    'i\'d be happy to',
    'i would be happy to',
    'certainly!',
    'absolutely!',
    'great question',
    'that\'s a great question',
    'as an ai',
    'as a language model',
    'i don\'t have personal',
    'i cannot provide',
    'delve into',
    'delve deeper',
    'it\'s crucial',
    'it is crucial',
    'it\'s essential',
    'it is essential',
    'furthermore',
    'moreover',
    'additionally',
    'in essence',
    'ultimately',
    'fundamentally',
    'inherently',
    'comprehensive understanding',
    'nuanced understanding',
    'multifaceted',
    'paradigm',
    'synergy',
    'leverage',
    'utilize',
    'facilitate',
    'in the realm of',
    'in today\'s world',
    'in this day and age',
    'plays a crucial role',
    'plays a vital role',
    'serves as a',
    'acts as a',
    'can be seen as',
    'it should be noted',
    'one might argue',
    'it goes without saying',
    'needless to say'
];

const AI_PATTERNS = [
    // Numbered lists with colons
    /^\d+\.\s+\w+:/gm,
    // Perfect bullet structure
    /^[-•]\s+\w+:/gm,
    // Overly formal transitions
    /\b(firstly|secondly|thirdly|lastly)\b/gi,
    // Triple structure (X, Y, and Z pattern repeated)
    /(\w+,\s+\w+,\s+and\s+\w+.*){2,}/gi,
    // Quotes around concepts (AI loves this)
    /"[\w\s]+" (refers to|means|is)/gi,
];

function detectAIContent(text) {
    const normalizedText = text.toLowerCase();
    const words = text.split(/\s+/).filter(w => w.length > 0);

    let aiScore = 0;
    const flags = [];

    // 1. Check for AI-specific phrases (max 40 points)
    let phraseMatches = 0;
    for (const phrase of AI_PHRASES) {
        if (normalizedText.includes(phrase)) {
            phraseMatches++;
            if (phraseMatches <= 3) {
                flags.push(`AI phrase: "${phrase}"`);
            }
        }
    }
    aiScore += Math.min(40, phraseMatches * 10);

    // 2. Check for AI patterns (max 20 points)
    let patternMatches = 0;
    for (const pattern of AI_PATTERNS) {
        if (pattern.test(text)) {
            patternMatches++;
        }
    }
    aiScore += Math.min(20, patternMatches * 7);
    if (patternMatches > 0) {
        flags.push(`Structural patterns: ${patternMatches} found`);
    }

    // 3. Sentence uniformity check (AI tends to write uniform sentence lengths) (max 15 points)
    const sentences = text.split(/[.!?]+/).filter(s => s.trim().length > 0);
    if (sentences.length >= 4) {
        const lengths = sentences.map(s => s.trim().split(/\s+/).length);
        const avgLength = lengths.reduce((a, b) => a + b, 0) / lengths.length;
        const variance = lengths.reduce((acc, l) => acc + Math.pow(l - avgLength, 2), 0) / lengths.length;
        const stdDev = Math.sqrt(variance);

        // Very low variance = robotic uniformity
        if (stdDev < 3 && avgLength > 10) {
            aiScore += 15;
            flags.push('Uniform sentence lengths (robotic)');
        } else if (stdDev < 5 && avgLength > 12) {
            aiScore += 8;
        }
    }

    // 4. Excessive formality ratio (max 15 points)
    const formalWords = ['therefore', 'thus', 'hence', 'consequently', 'nevertheless',
        'nonetheless', 'whereby', 'wherein', 'thereof', 'hereby'];
    let formalCount = 0;
    for (const word of formalWords) {
        const regex = new RegExp(`\\b${word}\\b`, 'gi');
        formalCount += (text.match(regex) || []).length;
    }
    const formalRatio = formalCount / words.length;
    if (formalRatio > 0.02) {
        aiScore += 15;
        flags.push('Excessive formal language');
    } else if (formalRatio > 0.01) {
        aiScore += 8;
    }

    // 5. Perfect punctuation and capitalization (max 10 points)
    const perfectCapitalization = sentences.every(s => {
        const trimmed = s.trim();
        return trimmed.length === 0 || /^[A-Z]/.test(trimmed);
    });
    if (perfectCapitalization && sentences.length > 3) {
        aiScore += 5;
    }

    // Determine confidence level
    const confidence = Math.min(100, aiScore);
    let verdict = 'human';
    if (confidence >= 60) {
        verdict = 'ai_generated';
    } else if (confidence >= 35) {
        verdict = 'suspicious';
    }

    return {
        isAI: confidence >= 50,
        confidence,
        verdict,
        flags: flags.slice(0, 5) // Max 5 flags
    };
}


/**
 * Evaluate a student's answer against the skill rubric
 * 
 * @param {string} skillId - The skill identifier
 * @param {string} answer - The student's answer
 * @param {boolean} demoMode - If true, always return a passing score
 * @returns {Object} Evaluation result with score, breakdown, feedback, and pass status
 */
export function evaluateAnswer(skillId, answer, demoMode = false) {
    // Demo mode: instant pass
    if (demoMode) {
        return {
            score: 95,
            breakdown: {
                keyphrases: 80,
                coherence: 15,
                matched: ['distributed ledger', 'immutable', 'consensus', 'decentralized', 'cryptographic']
            },
            feedback: "Excellent response! You've demonstrated a comprehensive understanding of the core concepts. Your explanation is clear, well-structured, and covers all the key points. NFT credential ready to mint!",
            pass: true,
            demoMode: true
        };
    }

    // Get skill rubric
    const skill = skills[skillId];
    if (!skill) {
        return {
            score: 0,
            breakdown: { error: 'Skill not found' },
            feedback: 'Error: Skill rubric not found.',
            pass: false
        };
    }

    const normalizedAnswer = preprocess(answer);
    const words = wordCount(answer);

    let keyphraseScore = 0;
    const matchedPhrases = [];
    const missedPhrases = [];

    // Check each keyphrase and its synonyms
    for (const kp of skill.keyphrases) {
        const allVariants = [kp.text, ...(kp.synonyms || [])];
        let found = false;

        for (const variant of allVariants) {
            if (containsPhrase(normalizedAnswer, variant)) {
                keyphraseScore += kp.weight;
                matchedPhrases.push(kp.text);
                found = true;
                break;
            }
        }

        if (!found) {
            missedPhrases.push(kp.text);
        }
    }

    // Cap keyphrase score at 90
    keyphraseScore = Math.min(90, keyphraseScore);

    // Coherence/length bonus (up to 10 points)
    let coherenceScore = 0;
    if (words >= 100) {
        coherenceScore = 10;
    } else if (words >= 75) {
        coherenceScore = 8;
    } else if (words >= 50) {
        coherenceScore = 5;
    } else if (words >= 30) {
        coherenceScore = 3;
    }

    // Penalty for very short answers
    let penalty = 0;
    if (words < 30) {
        penalty = 10;
    }

    // Calculate final score
    const rawScore = keyphraseScore + coherenceScore - penalty;
    const score = Math.max(0, Math.min(100, Math.round(rawScore)));

    // AI Detection
    const aiDetection = detectAIContent(answer);

    // Block pass if AI-generated content detected
    let pass = score >= skill.passThreshold;
    if (aiDetection.isAI && pass) {
        pass = false;
    }

    // Generate feedback
    let feedback = '';

    // AI Warning first
    if (aiDetection.isAI) {
        feedback = `⚠️ AI-Generated Content Detected (${aiDetection.confidence}% confidence). Your answer appears to be written by ChatGPT or similar AI. Please write your own answer to earn a credential. `;
    } else if (aiDetection.verdict === 'suspicious') {
        feedback = `⚡ Note: Some patterns in your answer raised minor flags (${aiDetection.confidence}% AI similarity), but your response is accepted. `;
    }

    if (pass) {
        if (score >= 85) {
            feedback += `Outstanding! You've demonstrated excellent understanding of ${skill.title}. `;
        } else if (score >= 70) {
            feedback += `Good work! You've shown solid grasp of the key concepts. `;
        } else {
            feedback += `You've passed with the minimum required score. `;
        }
        feedback += `Key concepts covered: ${matchedPhrases.slice(0, 3).join(', ')}. `;
        if (missedPhrases.length > 0 && score < 90) {
            feedback += `Consider also discussing: ${missedPhrases.slice(0, 2).join(', ')}.`;
        }
    } else if (aiDetection.isAI) {
        feedback += `Credential denied due to AI-generated content. Please rewrite your answer in your own words.`;
    } else {
        feedback = `Not quite there yet. Your answer needs more detail on: ${missedPhrases.slice(0, 3).join(', ')}. `;
        if (words < 30) {
            feedback += `Your response is too brief (${words} words). Aim for at least 50-100 words. `;
        }
        feedback += `Required score: ${skill.passThreshold}, your score: ${score}.`;
    }

    return {
        score,
        breakdown: {
            keyphrases: keyphraseScore,
            coherence: coherenceScore,
            penalty,
            matched: matchedPhrases,
            missed: missedPhrases,
            wordCount: words
        },
        aiDetection: {
            isAI: aiDetection.isAI,
            confidence: aiDetection.confidence,
            verdict: aiDetection.verdict,
            flags: aiDetection.flags
        },
        feedback: feedback.trim(),
        pass,
        threshold: skill.passThreshold
    };
}

/**
 * Get LLM prompt template for optional OSS LLM integration
 * 
 * This can be used with GPT4All, llama.cpp, or similar local LLMs.
 * The deterministic rubric above is always the fallback.
 */
export function getLLMPrompt(skillTitle, answer) {
    return `You are an impartial grader evaluating a student's answer for the skill: "${skillTitle}".

Student's Answer:
"""
${answer}
"""

Evaluate based on these criteria:
- Concept correctness (0-40 points): Is the core concept explained accurately?
- Coverage of key concepts (0-30 points): Are all important aspects mentioned?
- Clarity & reasoning (0-20 points): Is the explanation clear and logical?
- Examples/Insight (0-10 points): Are there practical examples or unique insights?

Return ONLY valid JSON in this exact format:
{
  "score": <number 0-100>,
  "breakdown": {
    "concept": <number 0-40>,
    "coverage": <number 0-30>,
    "clarity": <number 0-20>,
    "examples": <number 0-10>
  },
  "feedback": "<25-40 word constructive feedback>"
}`;
}

export default { evaluateAnswer, getLLMPrompt };
